// Class: Readgg_plus_trees100
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::gg_plus_trees100
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 6.02/05       [393733]
Creator        : dcurry
Date           : Fri Apr  7 06:15:26 2017
Host           : Linux vocms029.cern.ch 2.6.32-504.12.2.el6.x86_64 #1 SMP Thu Mar 12 07:33:00 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/d/dcurry/public/v25Heppy/CMSSW_7_4_7/src/VHbb/python
Training events: 108273
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.200000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "misclassificationerror" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass              HCMVAV2_reg_mass                                                'D'    [90.0014343262,149.999053955]
HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                HCMVAV2_reg_pt                                                  'D'    [0.647767603397,949.000488281]
VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb_deltaPhi_HCMVAV2_reg_phi,V_new_phi_  VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi) VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)                                               'D'    [-3.14158368111,3.1415784359]
hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0               hJetCMVA_btag_0                                                 'D'    [-0.586651742458,0.999979674816]
hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1               hJetCMVA_btag_1                                                 'D'    [-0.588379442692,0.999972224236]
hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                 hJetCMVA_pt_0                                                   'D'    [23.1669178009,904.850341797]
hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                 hJetCMVA_pt_1                                                   'D'    [24.3256206512,915.018066406]
V_new_mass                    V_new_mass                    V_new_mass                    V_new_mass                                                      'D'    [75.0050048828,104.998558044]
Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum__Jet_pt_reg_30__abs_Jet_eta__2.4__Jet_puId__7__Jet_id_0__aJCidx___hJCMVAV2idx_0_____aJCidx___hJCMVAV2idx_1____ Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1]))) Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))                                                                                                                        'D'    [0,8]
V_new_pt                      V_new_pt                      V_new_pt                      V_new_pt                                                        'D'    [150.000778198,2595.61816406]
(HCMVAV2_reg_pt/V_new_pt)     _HCMVAV2_reg_pt_D_V_new_pt_   (HCMVAV2_reg_pt/V_new_pt)     (HCMVAV2_reg_pt/V_new_pt)                                       'D'    [0.0024801325053,6.12399721146]
abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs_Jet_eta_hJCMVAV2idx_0___M_Jet_eta_hJCMVAV2idx_1___ abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])   abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])                                                              'D'    [1.73300504684e-05,3.33450603485]
softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5         softActivityVH_njets5                                           'D'    [0,18]
VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb_deltaR_HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi_  VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi) VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)                                                                       'D'    [0.0107788611203,6.80776691437]
met_pt                        met_pt                        met_pt                        met_pt                                                          'D'    [0.0728405341506,1414.9654541]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new gg_plus_trees100Node
   
#ifndef gg_plus_trees100Node__def
#define gg_plus_trees100Node__def
   
class gg_plus_trees100Node {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   gg_plus_trees100Node ( gg_plus_trees100Node* left,gg_plus_trees100Node* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~gg_plus_trees100Node();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   gg_plus_trees100Node* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   gg_plus_trees100Node* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   gg_plus_trees100Node*   fLeft;     // pointer to the left daughter node
   gg_plus_trees100Node*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   gg_plus_trees100Node::~gg_plus_trees100Node()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool gg_plus_trees100Node::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool gg_plus_trees100Node::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readgg_plus_trees100 : public IClassifierReader {

 public:

   // constructor
   Readgg_plus_trees100( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Readgg_plus_trees100" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "HCMVAV2_reg_mass", "HCMVAV2_reg_pt", "VHbb::deltaPhi(HCMVAV2_reg_phi,V_new_phi)", "hJetCMVA_btag_0", "hJetCMVA_btag_1", "hJetCMVA_pt_0", "hJetCMVA_pt_1", "V_new_mass", "Sum$(Jet_pt_reg>30&&abs(Jet_eta)<2.4&&Jet_puId==7&&Jet_id>0&&aJCidx!=(hJCMVAV2idx[0])&&(aJCidx!=(hJCMVAV2idx[1])))", "V_new_pt", "(HCMVAV2_reg_pt/V_new_pt)", "abs(Jet_eta[hJCMVAV2idx[0]]-Jet_eta[hJCMVAV2idx[1]])", "softActivityVH_njets5", "VHbb::deltaR(HCMVAV2_reg_eta,HCMVAV2_reg_phi,V_new_eta,V_new_phi)", "met_pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';
      fType[8] = 'D';
      fType[9] = 'D';
      fType[10] = 'D';
      fType[11] = 'D';
      fType[12] = 'D';
      fType[13] = 'D';
      fType[14] = 'D';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readgg_plus_trees100() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<gg_plus_trees100Node*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readgg_plus_trees100::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      gg_plus_trees100Node *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(gg_plus_trees100Node*)current->GetRight();
         else current=(gg_plus_trees100Node*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Readgg_plus_trees100::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.123871597579997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.743674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469517,-99) , 
0, 98.5725, 0, 0, 0.707219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421772,-99) , 
11, 1.41255, 1, 0, 0.674902,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.197755,-99) , 
3, 0.848872, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.112157);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.72202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48389,-99) , 
13, 3.33086, 1, 0, 0.696027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435333,-99) , 
1, 90.628, 0, 0, 0.661814,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.218628,-99) , 
3, 0.848872, 0, 0, 0.500744,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.103799);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.698126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449232,-99) , 
0, 95.7155, 0, 0, 0.675214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449008,-99) , 
11, 1.41255, 1, 0, 0.649027,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512828,-99) , 
NN(
0, 
0, 
0, 104.286, 0, -1, 0.191069,-99) , 
4, 0.163542, 0, 0, 0.238757,-99) , 
3, 0.848872, 0, 0, 0.501056,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0961747);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.707565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488131,-99) , 
4, -0.2102, 0, 0, 0.673557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465633,-99) , 
1, 90.3637, 0, 0, 0.645882,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552787,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.230254,-99) , 
4, 0.274985, 0, 0, 0.277943,-99) , 
3, 0.924426, 0, 0, 0.497376,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.0883477);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67781,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488876,-99) , 
1, 90.3637, 0, 0, 0.652751,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468219,-99) , 
0, 95.7156, 0, 0, 0.636468,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552641,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.252727,-99) , 
4, 0.346927, 0, 0, 0.290206,-99) , 
3, 0.924426, 0, 0, 0.497384,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0885896);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 98.5721, 0, 1, 0.679353,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591805,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414543,-99) , 
6, 65.966, 0, 0, 0.509807,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.271177,-99) , 
3, 0.924426, 0, 0, 0.363583,-99) , 
4, 0.394886, 0, 0, 0.496217,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0772859);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481304,-99) , 
0, 101.565, 0, 0, 0.619352,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440508,-99) , 
0, 138.571, 1, 0, 0.599561,-99) , 
NN(
0, 
0, 
0, 101.429, 0, -1, 0.266743,-99) , 
3, 0.773318, 0, 0, 0.494222,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0712036);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.661814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477607,-99) , 
13, 3.33086, 1, 0, 0.641041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463161,-99) , 
1, 90.628, 0, 0, 0.615657,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.338148,-99) , 
4, 0.0167069, 0, 0, 0.49496,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0723612);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469012,-99) , 
12, 4.28571, 1, 0, 0.605033,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387689,-99) , 
11, 1.56949, 1, 0, 0.587462,-99) , 
NN(
0, 
0, 
0, 104.286, 0, -1, 0.267816,-99) , 
3, 0.697764, 0, 0, 0.497427,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.059405);
  fForest.push_back( 
NN(
NN(
0, 
0, 
0, 98.5721, 0, 1, 0.635396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50829,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.364896,-99) , 
8, 0.380952, 1, 0, 0.392089,-99) , 
4, 0.394886, 0, 0, 0.494428,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0619428);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627259,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469411,-99) , 
14, 69.984, 1, 0, 0.611565,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382245,-99) , 
4, 0.621785, 0, 0, 0.461793,-99) , 
13, 3.25792, 1, 0, 0.586373,-99) , 
NN(
0, 
0, 
0, 98.5717, 0, -1, 0.350069,-99) , 
3, 0.924426, 0, 0, 0.493429,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0693516);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.650476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428776,-99) , 
0, 101.43, 0, 0, 0.61209,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54465,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417042,-99) , 
4, 0.697429, 0, 0, 0.468161,-99) , 
1, 135.965, 0, 0, 0.564461,-99) , 
NN(
0, 
0, 
0, 104.286, 0, -1, 0.279243,-99) , 
3, 0.62221, 0, 0, 0.493165,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0590092);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472109,-99) , 
1, 135.965, 0, 0, 0.599696,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365534,-99) , 
10, 0.812728, 1, 0, 0.468396,-99) , 
0, 101.429, 0, 0, 0.574331,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.367834,-99) , 
4, -0.0589289, 0, 0, 0.492578,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.057236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464083,-99) , 
13, 3.2593, 1, 0, 0.573088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382473,-99) , 
11, 1.58235, 1, 0, 0.55748,-99) , 
NN(
0, 
0, 
0, 107.146, 0, -1, 0.281615,-99) , 
3, 0.546656, 0, 0, 0.495555,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0520702);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475262,-99) , 
0, 101.565, 0, 0, 0.569096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415288,-99) , 
0, 138.571, 1, 0, 0.551599,-99) , 
NN(
0, 
0, 
0, 104.286, 0, -1, 0.312414,-99) , 
3, 0.62221, 0, 0, 0.492797,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0416289);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 101.429, 0, 1, 0.606574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487941,-99) , 
13, 3.25792, 1, 0, 0.586836,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517629,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.405705,-99) , 
12, 0.809524, 1, 0, 0.423301,-99) , 
4, 0.394886, 0, 0, 0.492182,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0542303);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456604,-99) , 
0, 104.287, 0, 0, 0.583929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424693,-99) , 
11, 0.791341, 1, 0, 0.466704,-99) , 
1, 135.965, 0, 0, 0.544456,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.29448,-99) , 
3, 0.471103, 0, 0, 0.493368,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0415407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493551,-99) , 
0, 101.429, 0, 0, 0.582429,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415109,-99) , 
4, 0.647034, 0, 0, 0.470563,-99) , 
8, 2.28571, 1, 0, 0.554273,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.397593,-99) , 
4, -0.0589289, 0, 0, 0.492701,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0464166);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462356,-99) , 
11, 1.26588, 1, 0, 0.566294,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512144,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436007,-99) , 
4, 0.924347, 0, 0, 0.456587,-99) , 
8, 2.28571, 1, 0, 0.539512,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.313008,-99) , 
3, 0.471103, 0, 0, 0.493695,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0458882);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46757,-99) , 
0, 104.287, 0, 0, 0.569276,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429552,-99) , 
0, 109.995, 1, 0, 0.468508,-99) , 
1, 135.965, 0, 0, 0.535186,-99) , 
NN(
0, 
0, 
0, 107.142, 0, -1, 0.323096,-99) , 
3, 0.471103, 0, 0, 0.492472,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0391016);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437583,-99) , 
7, 95.0005, 1, 0, 0.554134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383733,-99) , 
0, 141.425, 1, 0, 0.54079,-99) , 
NN(
0, 
0, 
0, 101.435, 0, -1, 0.40185,-99) , 
4, -0.134565, 0, 0, 0.492031,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0392399);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 104.286, 0, 1, 0.609109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488626,-99) , 
8, 2.28571, 1, 0, 0.577826,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438526,-99) , 
6, 66.5568, 0, 0, 0.516931,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.41186,-99) , 
12, 1.71429, 1, 0, 0.45166,-99) , 
4, 0.697429, 0, 0, 0.491322,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0409077);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453494,-99) , 
13, 3.24744, 1, 0, 0.545687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415072,-99) , 
0, 138.571, 1, 0, 0.530666,-99) , 
NN(
0, 
0, 
0, 109.998, 0, -1, 0.330371,-99) , 
3, 0.395549, 0, 0, 0.493482,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0299427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
0, 104.286, 0, 1, 0.595364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492756,-99) , 
8, 2.28571, 1, 0, 0.568625,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430304,-99) , 
11, 0.158811, 1, 0, 0.438034,-99) , 
8, 0.380952, 1, 0, 0.456242,-99) , 
4, 0.697429, 0, 0, 0.491576,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0390041);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467441,-99) , 
0, 104.287, 0, 0, 0.556452,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446911,-99) , 
1, 116.638, 0, 0, 0.468857,-99) , 
1, 135.965, 0, 0, 0.526737,-99) , 
NN(
0, 
0, 
0, 109.998, 0, -1, 0.342532,-99) , 
3, 0.395549, 0, 0, 0.49274,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0375193);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619062,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48486,-99) , 
6, 64.7337, 0, 0, 0.552272,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447975,-99) , 
2, 2.84235, 0, 0, 0.472091,-99) , 
5, 65.1518, 0, 0, 0.524841,-99) , 
NN(
0, 
0, 
0, 109.998, 0, -1, 0.351382,-99) , 
3, 0.395549, 0, 0, 0.492925,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0345692);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55689,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462774,-99) , 
13, 3.24744, 1, 0, 0.539991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42248,-99) , 
0, 138.571, 1, 0, 0.526491,-99) , 
NN(
0, 
0, 
0, 109.998, 0, -1, 0.359992,-99) , 
3, 0.395549, 0, 0, 0.495939,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0338117);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485136,-99) , 
11, 1.2556, 1, 0, 0.560774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42605,-99) , 
4, -0.437086, 0, 0, 0.539547,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472845,-99) , 
6, 65.784, 0, 0, 0.525985,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.415562,-99) , 
4, 0.697425, 0, 0, 0.450537,-99) , 
8, 1.14286, 1, 0, 0.494312,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0335496);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561802,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45896,-99) , 
0, 138.569, 1, 0, 0.549406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451852,-99) , 
2, 2.84235, 0, 0, 0.470581,-99) , 
5, 65.1518, 0, 0, 0.522181,-99) , 
NN(
0, 
0, 
0, 112.853, 0, -1, 0.337524,-99) , 
3, 0.244441, 0, 0, 0.495275,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0330668);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464611,-99) , 
0, 104.286, 0, 0, 0.549903,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445883,-99) , 
4, 0.816283, 0, 0, 0.473711,-99) , 
5, 65.1518, 0, 0, 0.523138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507446,-99) , 
NN(
0, 
0, 
0, 110.003, 0, -1, 0.362792,-99) , 
3, 0.924424, 0, 0, 0.40978,-99) , 
4, -0.285836, 0, 0, 0.494142,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0292314);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56375,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482681,-99) , 
0, 135.71, 1, 0, 0.55171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437981,-99) , 
4, -0.437086, 0, 0, 0.533805,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473403,-99) , 
6, 65.784, 0, 0, 0.517381,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.425156,-99) , 
4, 0.697425, 0, 0, 0.454447,-99) , 
8, 1.14286, 1, 0, 0.493473,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0381997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442735,-99) , 
0, 104.287, 0, 0, 0.586414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431534,-99) , 
5, 50.0771, 0, 0, 0.459079,-99) , 
5, 63.5325, 0, 0, 0.527769,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542104,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507181,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405246,-99) , 
4, 0.848693, 0, 0, 0.4255,-99) , 
6, 54.6206, 0, 0, 0.448174,-99) , 
6, 66.7395, 0, 0, 0.494206,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0284913);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459762,-99) , 
13, 3.28399, 1, 0, 0.544629,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425827,-99) , 
3, 0.321515, 0, 0, 0.526886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507826,-99) , 
NN(
0, 
0, 
0, 101.43, 0, -1, 0.428308,-99) , 
4, 0.848707, 0, 0, 0.446659,-99) , 
12, 2.57143, 1, 0, 0.494659,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0337361);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451203,-99) , 
0, 104.287, 0, 0, 0.580005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524143,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444255,-99) , 
4, 0.848709, 0, 0, 0.463018,-99) , 
5, 63.5325, 0, 0, 0.526062,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532133,-99) , 
NN(
0, 
0, 
0, 98.5719, 1, -1, 0.431406,-99) , 
6, 54.6206, 0, 0, 0.451021,-99) , 
6, 66.7395, 0, 0, 0.494411,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0292672);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539676,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440462,-99) , 
0, 138.569, 1, 0, 0.528087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382619,-99) , 
7, 96.4313, 1, 0, 0.517634,-99) , 
NN(
0, 
0, 
0, 115.709, 0, -1, 0.347081,-99) , 
3, 0.168887, 0, 0, 0.496199,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.025534);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451185,-99) , 
0, 104.285, 0, 0, 0.548431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466941,-99) , 
1, 135.208, 0, 0, 0.527848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511951,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.44879,-99) , 
12, 1.71429, 1, 0, 0.459242,-99) , 
8, 1.14286, 1, 0, 0.492993,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0303657);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459531,-99) , 
0, 104.287, 0, 0, 0.572106,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431227,-99) , 
5, 44.3106, 0, 0, 0.466329,-99) , 
5, 63.5325, 0, 0, 0.523256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53939,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502979,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426097,-99) , 
6, 47.2141, 0, 0, 0.443745,-99) , 
6, 58.6599, 0, 0, 0.455584,-99) , 
6, 66.7395, 0, 0, 0.494697,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0229671);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46782,-99) , 
10, 1.1279, 1, 0, 0.540579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453112,-99) , 
4, -0.437086, 0, 0, 0.526885,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468671,-99) , 
0, 115.714, 0, 0, 0.507019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502029,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429612,-99) , 
4, 0.697425, 0, 0, 0.452226,-99) , 
11, 0.317588, 1, 0, 0.463539,-99) , 
8, 1.14286, 1, 0, 0.494694,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0276468);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592242,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466694,-99) , 
0, 104.287, 0, 0, 0.566989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447035,-99) , 
2, 2.84235, 0, 0, 0.466853,-99) , 
5, 63.5325, 0, 0, 0.520705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530655,-99) , 
NN(
0, 
0, 
0, 98.5719, 1, -1, 0.44771,-99) , 
6, 58.6599, 0, 0, 0.457992,-99) , 
6, 66.7395, 0, 0, 0.494229,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0259334);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541051,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464117,-99) , 
13, 3.2593, 1, 0, 0.528117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404911,-99) , 
7, 95.7513, 1, 0, 0.453806,-99) , 
7, 93.5755, 1, 0, 0.515202,-99) , 
NN(
0, 
0, 
0, 115.709, 0, -1, 0.360428,-99) , 
3, 0.168887, 0, 0, 0.495939,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0221693);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487252,-99) , 
0, 111.767, 0, 0, 0.536243,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452226,-99) , 
0, 135.71, 1, 0, 0.523334,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54357,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466904,-99) , 
8, 2.28571, 1, 0, 0.505322,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.454287,-99) , 
11, 0.317588, 1, 0, 0.464833,-99) , 
8, 1.14286, 1, 0, 0.493612,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0236515);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457287,-99) , 
0, 138.569, 1, 0, 0.526305,-99) , 
NN(
0, 
0, 
0, 110.005, 0, -1, 0.456212,-99) , 
7, 93.5755, 1, 0, 0.514133,-99) , 
NN(
0, 
0, 
0, 115.709, 0, -1, 0.368624,-99) , 
3, 0.168887, 0, 0, 0.496098,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.022177);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461846,-99) , 
10, 0.576254, 0, 0, 0.533588,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443438,-99) , 
13, 3.28399, 1, 0, 0.518425,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501952,-99) , 
NN(
0, 
0, 
0, 101.43, 1, -1, 0.447839,-99) , 
11, 0.317594, 1, 0, 0.45862,-99) , 
12, 2.57143, 1, 0, 0.494421,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0228324);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480428,-99) , 
8, 2.28571, 1, 0, 0.533221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463823,-99) , 
2, 2.84236, 0, 0, 0.479289,-99) , 
5, 65.1518, 0, 0, 0.514182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509342,-99) , 
NN(
0, 
0, 
0, 110.003, 0, -1, 0.399852,-99) , 
3, 0.924424, 0, 0, 0.436201,-99) , 
4, -0.285836, 0, 0, 0.494525,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.024285);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47897,-99) , 
0, 112.857, 0, 0, 0.557081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511354,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451667,-99) , 
5, 48.1549, 0, 0, 0.471433,-99) , 
5, 63.5325, 0, 0, 0.517465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522129,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436983,-99) , 
4, 0.697425, 0, 0, 0.454367,-99) , 
6, 58.6599, 0, 0, 0.46278,-99) , 
6, 66.7395, 0, 0, 0.494374,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0213049);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467291,-99) , 
13, 3.2593, 1, 0, 0.52404,-99) , 
NN(
0, 
0, 
0, 112.86, 0, -1, 0.459375,-99) , 
7, 93.5759, 1, 0, 0.512853,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503637,-99) , 
NN(
0, 
0, 
0, 115.716, 0, -1, 0.375768,-99) , 
3, 0.773317, 0, 0, 0.426202,-99) , 
4, -0.361472, 0, 0, 0.49509,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0227846);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46338,-99) , 
10, 1.1727, 1, 0, 0.553824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461116,-99) , 
4, 0.848709, 0, 0, 0.472329,-99) , 
5, 63.5325, 0, 0, 0.516113,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514467,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441847,-99) , 
6, 47.2141, 0, 0, 0.45578,-99) , 
6, 58.6599, 0, 0, 0.46307,-99) , 
6, 66.7395, 0, 0, 0.493709,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0170826);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489093,-99) , 
0, 111.767, 0, 0, 0.529913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457716,-99) , 
0, 135.71, 1, 0, 0.518831,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504096,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.463857,-99) , 
12, 1.71429, 1, 0, 0.47052,-99) , 
8, 1.14286, 1, 0, 0.494293,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0229224);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429324,-99) , 
10, 1.14743, 1, 0, 0.5217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444674,-99) , 
0, 138.569, 1, 0, 0.512715,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505078,-99) , 
NN(
0, 
0, 
0, 112.863, 0, -1, 0.387649,-99) , 
12, 1.52381, 1, 0, 0.43069,-99) , 
4, -0.361472, 0, 0, 0.495942,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0358814);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493043,-99) , 
8, 2.28571, 1, 0, 0.57381,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634417,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321562,-99) , 
10, 0.942326, 1, 0, 0.431316,-99) , 
0, 112.858, 0, 0, 0.52155,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451693,-99) , 
10, 0.457169, 0, 0, 0.511629,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424174,-99) , 
14, 23.4253, 1, 0, 0.450628,-99) , 
0, 109.999, 1, 0, 0.473844,-99) , 
1, 181.286, 0, 0, 0.493738,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0344296);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494744,-99) , 
6, 67.3767, 0, 0, 0.576309,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621387,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345072,-99) , 
10, 0.942326, 1, 0, 0.442642,-99) , 
0, 115.715, 0, 0, 0.519469,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455123,-99) , 
3, 0.773561, 0, 0, 0.506249,-99) , 
NN(
0, 
0, 
0, 124.557, 1, -1, 0.433385,-99) , 
0, 118.57, 1, 0, 0.474545,-99) , 
1, 181.286, 0, 0, 0.493255,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0318716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585189,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49803,-99) , 
8, 2.28571, 1, 0, 0.565507,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337129,-99) , 
10, 0.942326, 1, 0, 0.435793,-99) , 
0, 112.858, 0, 0, 0.518105,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543483,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452137,-99) , 
0, 124.283, 1, 0, 0.511047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519711,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451543,-99) , 
9, 249.643, 0, 0, 0.460618,-99) , 
1, 146.877, 0, 0, 0.476033,-99) , 
1, 181.286, 0, 0, 0.493534,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0190863);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523857,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461797,-99) , 
0, 138.569, 1, 0, 0.516604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412206,-99) , 
7, 96.4313, 1, 0, 0.509188,-99) , 
NN(
0, 
0, 
0, 115.709, 0, -1, 0.3904,-99) , 
3, 0.168887, 0, 0, 0.494686,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0203377);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477183,-99) , 
0, 115.714, 0, 0, 0.543653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460859,-99) , 
7, 89.2828, 1, 0, 0.472939,-99) , 
5, 63.5325, 0, 0, 0.510783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510017,-99) , 
NN(
0, 
0, 
0, 98.5719, 1, -1, 0.461725,-99) , 
6, 58.6599, 0, 0, 0.467729,-99) , 
6, 66.7395, 0, 0, 0.492569,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.029118);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443561,-99) , 
14, 46.7046, 1, 0, 0.526701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407231,-99) , 
10, 0.861404, 1, 0, 0.485222,-99) , 
0, 112.857, 0, 0, 0.509332,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502507,-99) , 
NN(
0, 
0, 
0, 115.716, 0, -1, 0.39365,-99) , 
3, 0.773317, 0, 0, 0.436917,-99) , 
4, -0.361472, 0, 0, 0.494573,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0205053);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484779,-99) , 
0, 115.714, 0, 0, 0.544551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435998,-99) , 
6, 36.0022, 0, 0, 0.478219,-99) , 
6, 65.1939, 0, 0, 0.50988,-99) , 
NN(
0, 
0, 
0, 98.5725, 0, -1, 0.462428,-99) , 
5, 65.1518, 0, 0, 0.492872,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0184688);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.569301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472676,-99) , 
13, 3.17403, 1, 0, 0.541054,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507719,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439981,-99) , 
5, 38.5442, 0, 0, 0.478863,-99) , 
5, 63.5325, 0, 0, 0.51212,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500066,-99) , 
NN(
0, 
0, 
0, 98.5719, 1, -1, 0.465571,-99) , 
6, 58.6599, 0, 0, 0.46987,-99) , 
6, 66.7395, 0, 0, 0.494246,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0142227);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551142,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492813,-99) , 
0, 111.767, 0, 0, 0.524097,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464278,-99) , 
0, 135.71, 1, 0, 0.514916,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49457,-99) , 
4, 0.24378, 0, 0, 0.505758,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.4681,-99) , 
13, 2.27644, 1, 0, 0.47567,-99) , 
8, 1.14286, 1, 0, 0.494939,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0180226);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524396,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460634,-99) , 
0, 138.569, 1, 0, 0.516893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414288,-99) , 
7, 96.4315, 1, 0, 0.509697,-99) , 
NN(
0, 
0, 
0, 112.861, 1, -1, 0.422025,-99) , 
4, -0.437108, 0, 0, 0.496552,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0149851);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539476,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448571,-99) , 
10, 1.12938, 1, 0, 0.525644,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477984,-99) , 
11, 1.09865, 1, 0, 0.513476,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493897,-99) , 
11, 0.750426, 1, 0, 0.504052,-99) , 
NN(
0, 
0, 
0, 98.573, 0, -1, 0.469832,-99) , 
13, 2.27644, 1, 0, 0.476709,-99) , 
8, 1.14286, 1, 0, 0.494761,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0229921);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453066,-99) , 
0, 135.711, 1, 0, 0.515588,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346041,-99) , 
0, 121.429, 0, 0, 0.455782,-99) , 
10, 1.14684, 1, 0, 0.507806,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370898,-99) , 
3, 0.0177793, 0, 0, 0.495808,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0225964);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474129,-99) , 
5, 51.6098, 0, 0, 0.558719,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540288,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386999,-99) , 
10, 0.933951, 1, 0, 0.460295,-99) , 
0, 115.715, 0, 0, 0.517264,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562093,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47942,-99) , 
2, -3.0846, 1, 0, 0.506835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453561,-99) , 
2, 2.85663, 0, 0, 0.470916,-99) , 
2, -2.84239, 1, 0, 0.480531,-99) , 
6, 109.153, 0, 0, 0.493069,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0211772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479801,-99) , 
5, 51.6098, 0, 0, 0.5575,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392386,-99) , 
10, 0.933951, 1, 0, 0.460465,-99) , 
0, 115.715, 0, 0, 0.51663,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534276,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469126,-99) , 
6, 45.0757, 0, 0, 0.508754,-99) , 
NN(
0, 
0, 
0, 98.572, 1, -1, 0.472342,-99) , 
2, -2.84239, 1, 0, 0.482088,-99) , 
6, 109.153, 0, 0, 0.49387,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0173824);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449651,-99) , 
14, 69.9213, 1, 0, 0.515962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423422,-99) , 
3, 0.018833, 0, 0, 0.508303,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376727,-99) , 
13, 3.417, 1, 0, 0.440396,-99) , 
13, 3.24744, 1, 0, 0.496013,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0170926);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463726,-99) , 
11, 1.21244, 1, 0, 0.524952,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42179,-99) , 
13, 3.30692, 1, 0, 0.462581,-99) , 
13, 3.17051, 1, 0, 0.507727,-99) , 
NN(
0, 
0, 
0, 98.5725, 0, -1, 0.468538,-99) , 
5, 65.1518, 0, 0, 0.493672,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0195675);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475788,-99) , 
0, 136.94, 1, 0, 0.55473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395769,-99) , 
10, 0.933951, 1, 0, 0.459665,-99) , 
0, 115.715, 0, 0, 0.514632,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552657,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480662,-99) , 
2, -3.0846, 1, 0, 0.50449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500232,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467777,-99) , 
9, 238.397, 0, 0, 0.475298,-99) , 
2, -2.84239, 1, 0, 0.483112,-99) , 
6, 109.153, 0, 0, 0.493857,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.0158841);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423974,-99) , 
1, 361.942, 1, 0, 0.512865,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418544,-99) , 
7, 96.4315, 1, 0, 0.506265,-99) , 
NN(
0, 
0, 
0, 112.861, 1, -1, 0.430991,-99) , 
4, -0.437108, 0, 0, 0.495034,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.0174182);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48382,-99) , 
10, 0.947593, 0, 0, 0.55134,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399018,-99) , 
10, 0.933951, 1, 0, 0.458044,-99) , 
0, 115.715, 0, 0, 0.51198,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486639,-99) , 
6, 65.0652, 0, 0, 0.506762,-99) , 
NN(
0, 
0, 
0, 98.572, 1, -1, 0.478222,-99) , 
11, 0.317588, 1, 0, 0.483366,-99) , 
6, 109.153, 0, 0, 0.493115,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.0152908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454316,-99) , 
14, 69.9213, 1, 0, 0.51335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431531,-99) , 
3, 0.018833, 0, 0, 0.506609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386852,-99) , 
13, 3.417, 1, 0, 0.444697,-99) , 
13, 3.24744, 1, 0, 0.495425,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.018878);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485436,-99) , 
2, -2.98488, 1, 0, 0.533233,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464157,-99) , 
13, 3.21991, 1, 0, 0.51312,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464343,-99) , 
2, 3.0059, 0, 0, 0.514037,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447016,-99) , 
9, 233.573, 0, 0, 0.463731,-99) , 
2, 2.85663, 0, 0, 0.484812,-99) , 
2, -2.84239, 1, 0, 0.493361,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0168268);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491744,-99) , 
4, 0.319355, 1, 0, 0.531329,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468887,-99) , 
13, 3.21991, 1, 0, 0.513145,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533283,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469046,-99) , 
2, 3.0059, 0, 0, 0.512387,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502035,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451688,-99) , 
9, 233.573, 0, 0, 0.46578,-99) , 
2, 2.85663, 0, 0, 0.485312,-99) , 
2, -2.84239, 1, 0, 0.493717,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0157008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492198,-99) , 
0, 112.856, 0, 0, 0.531213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473107,-99) , 
13, 3.21991, 1, 0, 0.514291,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473809,-99) , 
11, 0.879064, 1, 0, 0.510915,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.467609,-99) , 
2, 2.85663, 0, 0, 0.485758,-99) , 
2, -2.84239, 1, 0, 0.494374,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0195284);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469561,-99) , 
0, 132.854, 1, 0, 0.513247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358098,-99) , 
0, 121.429, 0, 0, 0.455401,-99) , 
10, 1.14684, 1, 0, 0.50576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39202,-99) , 
3, 0.0177793, 0, 0, 0.495924,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0151331);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487144,-99) , 
2, -2.98488, 1, 0, 0.528569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474916,-99) , 
13, 3.21991, 1, 0, 0.512937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478789,-99) , 
2, 3.06017, 0, 0, 0.507811,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454829,-99) , 
13, 2.27644, 1, 0, 0.469703,-99) , 
2, 2.85663, 0, 0, 0.485673,-99) , 
2, -2.84239, 1, 0, 0.493904,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0148772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473586,-99) , 
11, 1.21244, 1, 0, 0.522302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504418,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419757,-99) , 
0, 115.715, 0, 0, 0.464135,-99) , 
13, 3.17051, 1, 0, 0.506252,-99) , 
NN(
0, 
0, 
0, 98.5725, 0, -1, 0.473542,-99) , 
5, 65.1518, 0, 0, 0.494518,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0152939);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474608,-99) , 
12, 0.142857, 0, 0, 0.522892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463465,-99) , 
12, 3.2381, 1, 0, 0.513016,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480603,-99) , 
12, 1.33333, 1, 0, 0.507902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355056,-99) , 
13, 2.92377, 1, 0, 0.471414,-99) , 
2, 2.85663, 0, 0, 0.486704,-99) , 
2, -2.84239, 1, 0, 0.494647,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0179404);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457384,-99) , 
10, 0.873632, 0, 0, 0.536449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445303,-99) , 
14, 35.5581, 0, 0, 0.487289,-99) , 
0, 115.713, 0, 0, 0.51227,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483058,-99) , 
2, 3.06017, 0, 0, 0.50802,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.469134,-99) , 
2, 2.85663, 0, 0, 0.485429,-99) , 
2, -2.84239, 1, 0, 0.493531,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0143407);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454875,-99) , 
7, 95.0037, 1, 0, 0.511031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416176,-99) , 
1, 361.942, 1, 0, 0.505008,-99) , 
NN(
0, 
0, 
0, 112.861, 1, -1, 0.439501,-99) , 
4, -0.437108, 0, 0, 0.495271,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0169497);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460086,-99) , 
10, 0.873632, 0, 0, 0.533754,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44818,-99) , 
4, 0.167974, 1, 0, 0.486045,-99) , 
0, 115.713, 0, 0, 0.510282,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4759,-99) , 
11, 0.879064, 1, 0, 0.506772,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460452,-99) , 
9, 233.573, 0, 0, 0.472006,-99) , 
2, 2.85663, 0, 0, 0.486576,-99) , 
2, -2.84239, 1, 0, 0.49373,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0143008);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537098,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488564,-99) , 
0, 115.715, 0, 0, 0.515061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457197,-99) , 
6, 36.2336, 0, 0, 0.488216,-99) , 
6, 66.0037, 0, 0, 0.503757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397929,-99) , 
13, 3.417, 1, 0, 0.45004,-99) , 
13, 3.24744, 1, 0, 0.494082,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0141889);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488774,-99) , 
4, 0.319355, 1, 0, 0.523333,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47626,-99) , 
13, 3.21991, 1, 0, 0.509602,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453085,-99) , 
7, 93.567, 1, 0, 0.504914,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512743,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457973,-99) , 
4, 0.848698, 0, 0, 0.470576,-99) , 
13, 2.92377, 1, 0, 0.486867,-99) , 
2, -2.84239, 1, 0, 0.493725,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0127017);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487439,-99) , 
2, -2.98488, 1, 0, 0.52323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479819,-99) , 
13, 3.21991, 1, 0, 0.510566,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484584,-99) , 
12, 1.33333, 1, 0, 0.507223,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.472043,-99) , 
2, 2.85663, 0, 0, 0.486788,-99) , 
2, -2.84239, 1, 0, 0.493961,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.0215397);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42509,-99) , 
14, 69.9213, 1, 0, 0.513869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395543,-99) , 
0, 118.572, 0, 0, 0.475775,-99) , 
1, 226.446, 1, 0, 0.504241,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400111,-99) , 
3, 0.0177793, 0, 0, 0.495281,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0131223);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464335,-99) , 
12, 3.28571, 1, 0, 0.518925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472757,-99) , 
12, 0.809524, 0, 0, 0.508092,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519871,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47557,-99) , 
13, 3.18709, 1, 0, 0.504694,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.472489,-99) , 
2, 2.85663, 0, 0, 0.48599,-99) , 
2, -2.84239, 1, 0, 0.492655,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0197047);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471155,-99) , 
0, 136.94, 1, 0, 0.540552,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517211,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40858,-99) , 
10, 0.933951, 1, 0, 0.460647,-99) , 
0, 115.715, 0, 0, 0.506744,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444321,-99) , 
10, 0.810351, 1, 0, 0.505163,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463707,-99) , 
14, 24.1839, 1, 0, 0.479912,-99) , 
0, 104.286, 1, 0, 0.486663,-99) , 
6, 109.153, 0, 0, 0.493488,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0163058);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46033,-99) , 
10, 0.873632, 0, 0, 0.527008,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44873,-99) , 
14, 35.5581, 0, 0, 0.487726,-99) , 
0, 115.713, 0, 0, 0.507682,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459056,-99) , 
7, 87.8556, 0, 0, 0.506352,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460071,-99) , 
4, 0.848698, 0, 0, 0.470697,-99) , 
13, 2.92377, 1, 0, 0.487621,-99) , 
2, -2.84239, 1, 0, 0.493669,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0123392);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48174,-99) , 
0, 124.283, 1, 0, 0.519092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479332,-99) , 
1, 229.639, 1, 0, 0.507283,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484653,-99) , 
2, 3.06017, 0, 0, 0.505909,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500692,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370807,-99) , 
13, 2.92377, 1, 0, 0.474305,-99) , 
2, 2.85663, 0, 0, 0.487553,-99) , 
2, -2.84239, 1, 0, 0.4935,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0150919);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465604,-99) , 
10, 0.873632, 0, 0, 0.527551,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451259,-99) , 
14, 35.5581, 0, 0, 0.48666,-99) , 
0, 115.713, 0, 0, 0.507435,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479753,-99) , 
11, 0.879064, 1, 0, 0.506049,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.47246,-99) , 
2, 2.85663, 0, 0, 0.486541,-99) , 
2, -2.84239, 1, 0, 0.492838,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0140938);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469363,-99) , 
10, 0.873632, 0, 0, 0.526458,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454439,-99) , 
4, 0.167974, 1, 0, 0.487039,-99) , 
0, 115.713, 0, 0, 0.507065,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486096,-99) , 
12, 1.33333, 1, 0, 0.505164,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377229,-99) , 
13, 2.92377, 1, 0, 0.476223,-99) , 
2, 2.85663, 0, 0, 0.488356,-99) , 
2, -2.84239, 1, 0, 0.493993,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.013617);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472877,-99) , 
10, 0.873632, 0, 0, 0.525436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455585,-99) , 
14, 35.5581, 0, 0, 0.487499,-99) , 
0, 115.713, 0, 0, 0.50677,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472611,-99) , 
0, 104.287, 0, 0, 0.505274,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.474112,-99) , 
2, 2.85663, 0, 0, 0.487177,-99) , 
2, -2.84239, 1, 0, 0.493079,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.0129967);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515214,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465083,-99) , 
5, 39.1718, 0, 0, 0.508272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415402,-99) , 
1, 361.942, 1, 0, 0.502403,-99) , 
NN(
0, 
0, 
0, 112.861, 1, -1, 0.444855,-99) , 
4, -0.437108, 0, 0, 0.493864,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0146005);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47465,-99) , 
10, 0.873632, 0, 0, 0.523191,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456342,-99) , 
4, 0.167974, 1, 0, 0.486564,-99) , 
0, 115.713, 0, 0, 0.505169,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544378,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486657,-99) , 
9, 233.573, 0, 0, 0.503105,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460587,-99) , 
7, 89.2902, 1, 0, 0.472876,-99) , 
13, 2.92377, 1, 0, 0.487243,-99) , 
2, -2.84239, 1, 0, 0.492642,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0156486);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52907,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460546,-99) , 
7, 87.3812, 0, 0, 0.515631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456437,-99) , 
7, 93.5695, 1, 0, 0.505031,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544147,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46148,-99) , 
8, 1.14286, 1, 0, 0.509911,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521095,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469652,-99) , 
4, 0.924336, 0, 0, 0.47955,-99) , 
7, 89.2923, 1, 0, 0.487744,-99) , 
13, 2.92377, 1, 0, 0.493709,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0187058);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47131,-99) , 
0, 129.997, 1, 0, 0.511119,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405662,-99) , 
0, 118.572, 0, 0, 0.476371,-99) , 
1, 226.467, 1, 0, 0.502422,-99) , 
NN(
0, 
0, 
0, 115.709, 0, -1, 0.434308,-99) , 
3, 0.168887, 0, 0, 0.49431,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.017633);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479236,-99) , 
5, 51.6098, 0, 0, 0.535783,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527359,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426882,-99) , 
3, 0.925125, 1, 0, 0.46329,-99) , 
0, 115.715, 0, 0, 0.50512,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450087,-99) , 
10, 0.810351, 1, 0, 0.503266,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507798,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468087,-99) , 
14, 24.1839, 1, 0, 0.481118,-99) , 
0, 104.286, 1, 0, 0.487036,-99) , 
6, 109.153, 0, 0, 0.49317,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.011555);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474417,-99) , 
13, 3.21991, 1, 0, 0.515815,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472709,-99) , 
12, 0.809524, 0, 0, 0.505734,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479814,-99) , 
13, 3.18709, 1, 0, 0.504868,-99) , 
NN(
0, 
0, 
0, 98.5726, 0, -1, 0.476589,-99) , 
2, 2.85663, 0, 0, 0.488447,-99) , 
2, -2.84239, 1, 0, 0.493652,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0200551);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466232,-99) , 
10, 0.881447, 0, 0, 0.520322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450223,-99) , 
4, 0.0923395, 1, 0, 0.483124,-99) , 
0, 115.715, 0, 0, 0.5034,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518048,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451462,-99) , 
3, 0.62221, 0, 0, 0.503367,-99) , 
NN(
0, 
0, 
0, 110, 1, -1, 0.445689,-99) , 
6, 34.4239, 0, 0, 0.482419,-99) , 
6, 66.7395, 0, 0, 0.494491,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0136898);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545533,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464024,-99) , 
9, 185.82, 0, 0, 0.490258,-99) , 
9, 233.573, 0, 0, 0.505949,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488328,-99) , 
2, -3.0846, 1, 0, 0.50516,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469854,-99) , 
14, 56.6489, 0, 0, 0.475373,-99) , 
2, -2.84239, 1, 0, 0.488477,-99) , 
13, 2.92377, 1, 0, 0.49451,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0180772);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519685,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433069,-99) , 
14, 69.9213, 1, 0, 0.512268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535687,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41121,-99) , 
0, 118.572, 0, 0, 0.475261,-99) , 
1, 226.446, 1, 0, 0.502966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415665,-99) , 
3, 0.0177793, 0, 0, 0.495496,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0150458);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455147,-99) , 
8, 2.28571, 1, 0, 0.524617,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443085,-99) , 
0, 107.144, 0, 0, 0.504089,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463741,-99) , 
4, 0.848701, 1, 0, 0.502345,-99) , 
NN(
0, 
0, 
0, 98.5719, 0, -1, 0.478958,-99) , 
6, 64.7182, 0, 0, 0.487739,-99) , 
6, 109.153, 0, 0, 0.493282,-99)    );
   return;
};
 
// Clean up
inline void Readgg_plus_trees100::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Readgg_plus_trees100::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
